In [1]:
# This script is based on:
# https://www.tensorflow.org/get_started/mnist/pros

import sys
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.python.framework import graph_util as gu
from tensorflow.python.framework.graph_util import remove_training_nodes
from tensorflow.tools.graph_transforms import TransformGraph

/Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/yuezha

# Import training data

In [2]:
mnist = input_data.read_data_sets("mnist_data/", one_hot=True)

W1009 11:19:01.997934 4533585344 deprecation.py:323] From <ipython-input-2-08601696ce79>:1: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W1009 11:19:01.999318 4533585344 deprecation.py:323] From /Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W1009 11:19:02.003123 4533585344 deprecation.py:323] From /Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecat

Extracting mnist_data/train-images-idx3-ubyte.gz


W1009 11:19:02.237914 4533585344 deprecation.py:323] From /Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
W1009 11:19:02.240267 4533585344 deprecation.py:323] From /Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
W1009 11:19:02.311156 4533585344 deprecation.py:323] From /Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (f

Extracting mnist_data/train-labels-idx1-ubyte.gz
Extracting mnist_data/t10k-images-idx3-ubyte.gz
Extracting mnist_data/t10k-labels-idx1-ubyte.gz


# Define Tensorflow Model

### Fully connected 2 layer NN

In [3]:
def deepnn(x):
    W_fc1 = weight_variable([784, 128], name='W_fc1')
    b_fc1 = bias_variable([128], name='b_fc1')
    a_fc1 = tf.add(tf.matmul(x, W_fc1), b_fc1, name="zscore")
    h_fc1 = tf.nn.relu(a_fc1)
    
    W_fc2 = weight_variable([128, 64], name='W_fc2')
    b_fc2 = bias_variable([64], name='b_fc2')
    a_fc2 = tf.add(tf.matmul(h_fc1, W_fc2), b_fc2, name="zscore")
    h_fc2 = tf.nn.relu(a_fc2)
    
    W_fc3 = weight_variable([64, 10], name='W_fc3')
    b_fc3 = bias_variable([10], name='b_fc3')
    logits = tf.add(tf.matmul(h_fc2, W_fc3), b_fc3, name="logits")
    y_pred = tf.argmax(logits, 1, name='y_pred')

    return y_pred, logits


def weight_variable(shape, name):
    """weight_variable generates a weight variable of a given shape."""
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial, name)


def bias_variable(shape, name):
    """bias_variable generates a bias variable of a given shape."""
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial, name)

### Specify inputs, outputs, and a cost function

In [4]:
# Reset default graph
tf.reset_default_graph()

# Create the model
x = tf.placeholder(tf.float32, [None, 784], name="x")

# Define loss and optimizer
y_ = tf.placeholder(tf.float32, [None, 10], name="y")

# Build the graph for the deep net
y_pred, logits = deepnn(x)

with tf.name_scope("Loss"):
    cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y_, 
                                                               logits=logits)
    loss = tf.reduce_mean(cross_entropy, name="cross_entropy_loss")
train_step = tf.train.AdamOptimizer(1e-4).minimize(loss, name="train_step")
  
# Here we specify the output as "Prediction/y_pred", this will be important later
with tf.name_scope("Prediction"): 
    correct_prediction = tf.equal(y_pred, 
                                  tf.argmax(y_, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32), name="accuracy")

# Train the model

In [5]:
batch_size = 100
n_epochs = 100
n_batches = int(mnist.train.num_examples / batch_size)
print(n_batches)

550


In [6]:
sess = tf.Session()
# Initialize the variables (i.e. assign their default value)
sess.run(tf.global_variables_initializer())
saver = tf.train.Saver()

train_loss, train_accuracy = sess.run([loss, accuracy], feed_dict={x: mnist.train.images, y_: mnist.train.labels})
print('Epoch %d, training loss: %g, training accuracy: %g' % (0, train_loss, train_accuracy))
val_loss, val_accuracy = sess.run([loss, accuracy], feed_dict={x: mnist.validation.images,
                                                               y_: mnist.validation.labels})
print('Epoch %d, validation loss: %g, validation accuracy %g' % (0, val_loss, val_accuracy))

Epoch 0, training loss: 2.35022, training accuracy: 0.0861818
Epoch 0, validation loss: 2.35043, validation accuracy 0.086


In [7]:
for i in range(n_epochs):
    for j in range(n_batches):
        batch_images, batch_labels = mnist.train.next_batch(batch_size)
        sess.run(train_step, feed_dict={x: batch_images, y_: batch_labels})
        
    if i % 10 == 0:
        train_loss, train_accuracy = sess.run([loss, accuracy], feed_dict={x: mnist.train.images, 
                                                                           y_: mnist.train.labels})
        print('Epoch %d, training loss: %g, training accuracy: %g' % (i, train_loss, train_accuracy))
        val_loss, val_accuracy = sess.run([loss, accuracy], feed_dict={x: mnist.validation.images,
                                                                       y_: mnist.validation.labels})
        print('Epoch %d, validation loss: %g, validation accuracy %g' % (i, val_loss, val_accuracy))

Epoch 0, training loss: 0.456548, training accuracy: 0.880818
Epoch 0, validation loss: 0.433634, validation accuracy 0.8932
Epoch 10, training loss: 0.135838, training accuracy: 0.961236
Epoch 10, validation loss: 0.137302, validation accuracy 0.9612
Epoch 20, training loss: 0.081657, training accuracy: 0.976927
Epoch 20, validation loss: 0.0996873, validation accuracy 0.9716
Epoch 30, training loss: 0.0526297, training accuracy: 0.985236
Epoch 30, validation loss: 0.0850597, validation accuracy 0.9758
Epoch 40, training loss: 0.0345844, training accuracy: 0.991709
Epoch 40, validation loss: 0.0795974, validation accuracy 0.977
Epoch 50, training loss: 0.0219889, training accuracy: 0.995509
Epoch 50, validation loss: 0.0785264, validation accuracy 0.9778
Epoch 60, training loss: 0.0135292, training accuracy: 0.997964
Epoch 60, validation loss: 0.0791062, validation accuracy 0.9778
Epoch 70, training loss: 0.00800096, training accuracy: 0.999145
Epoch 70, validation loss: 0.0829583, va

## What is the final accuracy

In [8]:
print('test accuracy %g' % sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

test accuracy 0.9775


# Freeze the graph

In [9]:
saver.save(sess, "./chkps_mnist_mlp/mnist_model")
out_nodes = [y_pred.op.name]
print(out_nodes)

W1009 11:21:20.688085 4533585344 meta_graph.py:449] Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'W_fc1' has type str, but expected one of: int, long, bool
W1009 11:21:20.689682 4533585344 meta_graph.py:449] Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'W_fc1' has type str, but expected one of: int, long, bool


['y_pred']


### Remove unnecessary training nodes

In [10]:
sub_graph_def = remove_training_nodes(sess.graph_def)

W1009 11:21:33.769155 4533585344 deprecation.py:323] From <ipython-input-10-e3cb912a33e6>:1: remove_training_nodes (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.remove_training_nodes`


### Freeze Constants

In [11]:
sub_graph_def = gu.convert_variables_to_constants(sess, sub_graph_def, out_nodes)

W1009 11:21:39.615973 4533585344 deprecation.py:323] From <ipython-input-11-b3301d4c156e>:1: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W1009 11:21:39.617860 4533585344 deprecation.py:323] From /Users/yuezha01/anaconda3/envs/tensorflow_cpu/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:270: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`


### Quantize (removed because uTensor applies it in code gen)
* at least for utensor 0.3.3.dev2, both quantized and unquantized graphs work in uTensor code gen. The weights in .hpp look identical to me.

In [14]:
 quant_graph_def = TransformGraph(sub_graph_def,
                                  [],
                                  y_pred.op.name,
                                  ["quantize_weights", "quantize_nodes"])

In [15]:
graph_path = tf.train.write_graph(quant_graph_def,
                                  "./mnist_model_mlp_quant",
                                  "deep_mlp_quant.pb",
                                  as_text=False)

print('written graph to: %s' % graph_path)

written graph to: ./mnist_model_mlp_quant/deep_mlp_quant.pb


### Save the graph to PB file

In [12]:
graph_path = tf.train.write_graph(sub_graph_def,
                                  "./mnist_model_mlp_noquant",
                                  "deep_mlp.pb",
                                  as_text=False)

print('written graph to: %s' % graph_path)

written graph to: ./mnist_model_mlp_noquant/deep_mlp.pb


In [40]:
sess.run(y_pred, feed_dict={x: mnist.test.images[0:100, :]})

array([7, 2, 1, 0, 4, 1, 4, 9, 6, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2,
       3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 8, 3, 7, 4,
       6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
       6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9])

In [51]:
sess.run(y_pred, feed_dict={x: mnist.test.images[[3, 2, 1, 18, 4, 15, 11, 0, 61, 7], :]})

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
mnist.test.labels[[3, 2, 1, 18, 4, 15, 11, 0, 61, 7], :]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# close session
sess.close()